### ISSUE TITLE
Feedback and requests

### ISSUE THREAD

**Issue by OasisX** [satrik/toggleMute#13]
Hi Dev

Love your app, but have some feedback/requests:

1. Would be good if the menu bar icon was smaller so there's a gap top and bottom. Will look more in line with other icons and give "space" around the icon.
2. The app doesn't recognise when other mute toggles are invoked via other apps. So say your app is current on Unmute, and I press mute on my display monitor (it has a physical mute button), the monitor mic is muted (red light shows), but your app doesn't recognise and still shows unmute. Vice versa is true, if I mute your app but unmute on the monitor, the app still shows it's on mute, when it fact it's not. This latter example is dangerous because it might cause me to think my mic is muted when it's actually not. That's a recipe for disaster (like if I start singing during a zoom call because I think my mic is muted haha). 

Great work though.

**Comment by satrik** [comment]
hey @OasisX, thanks for the feedback.
1. this point is now on my todo list. I will try to fix and publish it with the next release
2. I'm not sure about that. the app only monitors the macOS builtin mute/unmute volume for the default selected input device. so if you have any sort of hardware mute, which does not just mute the input volume of macOS, then there is no chance to listen for changes because the OS does not even know if you are muted or not

**Comment by OasisX** [comment]
Interesting, it's not just hardware switches though, but also in apps. For example in Microsoft Teams, if I press mute inside the app, your menu bar toggle doesn't turn red. I assume the mic is muted as it shows mute in Teams, but your app visually indicates otherwise. And if I toggle your app to mute, in Teams, it doesn't show mute. 

I guess that's a limitation? I wish there was a global trigger that consistent reads "one source of truth" re the mic status.

**Comment by OasisX** [comment]
Thanks, so to confirm, if I mute using your app, it's a system wide mute and I can ignore the status of any mute icons/hardware LEDs (which may show "unmuted"), knowing that the mic is on mute per your app visual status. If I can just trust in your app's mute status, I won't have to worry about all the other ones.
