### ISSUE TITLE
[Feature request] Auto update

### ISSUE THREAD

**Issue by borsitsb** [satrik/toggleMute#14]
Hey,

Is there a way to auto-upgrade toggleMute? I always forget upgrading the app. It would be nice to have it available via brew, as it has an auto-upgrade feature available.
Thanks.

Cheers,
Botond

**Comment by borsitsb** [comment]
Awesome, thanks. For the record, brew was a solution proposal only from me. I'm happy to help elaborate on other auto-update solutions if that helps.
Can I support you by buying some coffee/beer? You spent a lot of time on this, which helps me a lot.

**Comment by satrik** [comment]
hey @borsitsb, brew is the best solution for me as well and I already finished the work 4 moth ago :D just didn't made the last few steps to push the changes, but now I had the time to do it.
you should now be able to install toggleMute via brew, I've updated the readme how to do it. would be nice to get some feedback if it works for you.
and I don't have accounts for buymeacoffee/beer, but thanks for the offer :)

**Comment by borsitsb** [comment]
Hey @satrik, I tested and it works like a charm. Thank you :)
