### ISSUE TITLE
Add Shortcut / Menu option to activate and deactivate

### ISSUE THREAD

**Issue by scrapix** [satrik/toggleMute#2]
Is it possible to add a menu item "active / deactivate" instead of just clicking the icon in the menubar? 
if so, it would allow to set a keyboard shortcut in osx.
As alternative a fixed shortcut would be great aswell.

**Comment by satrik** [comment]
I had the same idea a few weeks ago and started testing this, but didn't find the time to finish it^^ But today I had the time to get it done and pushed already the update.
