### ISSUE TITLE
Add tint to menu bar icon to indicate mute status

### ISSUE THREAD

**Issue by angelsanzn** [satrik/toggleMute#3]
Hi there! Many thanks for this great app. It even works with bluetooth headphones output and a different input in macOS Monterey.

Could you make the status bar icon red when the app is muting audio input? This would make it stand out a lot more, specially in high-res displays.

Thanks!

Edit: or even better, instead of red when muted, add an orange tint when the mic is unmuted, to keep color and UX in line with [the native audio capture indicator](https://www.macrumors.com/how-to/menu-bar-dot-explanation/).

**Comment by satrik** [comment]
hi, the dot just indicated if an app uses the microphone/camera. as this app just sets the system settings and don't use the microphone itself, the dot would be the wrong way. 

I've added an option to set the background of the menubar icon to red if the mic is muted.

**Comment by angelsanzn** [comment]
I know, I didn't mean to add a dot.

I mean to tint the unmute icon in the menu bar with the same color as the orange icon. This way the UX leverages the meanings already learned by users, but applied to the system level instead of to the app level.

No orange color (equivalent to no orange dot) = mic is closed to the system
Orange color (equivalent to orange dot) = mic is open to the system

I imagine there must be a way to tint the image template you use for the unmute icon, instead of filling the whole background. I found [this](https://stackoverflow.com/a/50074538). I'm sorry I can't be of more help, thanks anyway for the great work!
