### ISSUE TITLE
App doesn't work if launched when input volume is 0

### ISSUE THREAD

**Issue by angelsanzn** [satrik/toggleMute#4]
I tested this by quitting the app when the volume was muted, and then launching it again.

As soon as the input volume slider is moved to any point greater than 0, the app starts working.

As seen from the outside, the app seems to asume that the input volume will never be 0 when it launches.

**Comment by satrik** [comment]
Hmm, you're right. I never quit the app so I didn't noticed this 😄
I will fix this today.
