### ISSUE TITLE
Does not mute audio input from Airpods

### ISSUE THREAD

**Issue by angelsanzn** [satrik/toggleMute#5]
Having Airpods connected and set to default input device in System Preferences, regardless how I try to mute audio input using the app, it does not work.

I don't know whether this is specific to Airpods or happens with any Bluetooth audio input device.

**Comment by satrik** [comment]
sounds like an AirPods problem. I use 3 different bluetooth headsets and all 3 work without any issues.

**Comment by angelsanzn** [comment]
Are you on macOS Monterey?
