### ISSUE TITLE
Doesnt work on Monterey

### ISSUE THREAD

**Issue by HugoMinariAtlas** [satrik/toggleMute#6]
I've tested on monterey, but it don't mute the microphone

**Comment by jovobe** [comment]
I cannot confirm this. I am on macOS 12.6 (M1 Pro MacBook Pro) and the app is working fine.

**Comment by satrik** [comment]
Hey @HugoMinariAtlas, sorry for the late response. 
I'm also on 12.6 with 2 different MacBook Pros and don't have issues. 

So what exactly isn't working for you?
