### ISSUE TITLE
Doesn't work with iPhone mic

### ISSUE THREAD

**Issue by AshZadePM** [satrik/toggleMute#8]
Love ToggleMute and I use it with an external USB mic.

I noticed that it doesn't mute the iPhone mic when using it with Continuity Camera feature (iPhone as webcam & mic).

If ToggleMute works with the iPhone, then I don't need the external mic.

**Comment by satrik** [comment]
hey, as there is no option inside macOS to set the input volume for the iPhone, I can't do anything 🤷🏼‍♂️
